# services:
#   - type: web
#     name: e-commerce-churn-predictor
#     env: python
#     plan: free
#     buildCommand: ""
#     startCommand: gunicorn app:app
    


services:
  - type: web
    name: e-commerce-churn-predictor
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app