
pythonVersion: 3.13.4
services:
  - type: web
    name: e-commerce-churn-predictor
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python start.py
    envVars:
      - key: PYTHONUNBUFFERED
        value: "1"
